import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "ar" | "en" | "fr" | "tr" | "zh" | "es";

type DirectionType = "ltr" | "rtl";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  dir: DirectionType;
}

interface TranslationsType {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: TranslationsType = {
  ar: {
    "home": "الرئيسية",
    "services": "خدماتنا",
    "about": "من نحن",
    "portfolio": "أعمالنا",
    "contact": "اتصل بنا",
    "hero.title": "نقود التحول الرقمي من خلال الابتكار",
    "hero.subtitle": "نقدم حلول تقنية متكاملة تجمع بين الإبداع والتميز لنساعد الشركات على النمو في العصر الرقمي",
    "cta.button": "تواصل معنا",
    "services.title": "خدماتنا المتميزة",
    "services.description": "نوفر حلولًا رقمية مبتكرة تشمل تطوير المواقع والتطبيقات، الاستشارات التقنية، الحلول السحابية، وأمان المعلومات. نهدف إلى تحسين الأداء الرقمي لأعمالك عبر استراتيجيات متقدمة تضمن الكفاءة، الأمان، والتوسع المستدام. 🚀",
    "services.viewAll": "عرض الخدمات",
    "service1.title": "تطوير المواقع الإلكترونية",
    "service1.desc": "نصمم ونطور مواقع احترافية متوافقة مع محركات البحث، بأحدث التقنيات لضمان تجربة مستخدم سلسة وأداء مثالي على جميع الأجهزة.",
    "service2.title": "تطوير تطبيقات الجوال",
    "service2.desc": "برمجة تطبيقات مخصصة لأنظمة iOS وAndroid، تلبي احتياجات عملك، مع تصميم مبتكر وتجربة مستخدم متقدمة لزيادة التفاعل والانتشار.",
    "service3.title": "الاستشارات التقنية والتدريب",
    "service3.desc": "نوفر استشارات متخصصة لمساعدتك على اتخاذ قرارات تقنية ذكية، بالإضافة إلى دورات تدريبية متقدمة في مجالات تكنولوجيا المعلومات لضمان رفع كفاءة فريقك.",
    "service4.title": "أمان المعلومات",
    "service4.desc": "حلول متقدمة لحماية بياناتك وشبكاتك من التهديدات السيبرانية، من خلال أنظمة أمان حديثة وفحوصات دورية لضمان الأمان الرقمي.",
    "footer.copyright": "جميع الحقوق محفوظة",
    "about.title": "من نحن",
    "about.subtitle": "نبتكر اليوم، لنرتقي بالغد",
    "about.description": "نحن شركة متخصصة في تقديم حلول رقمية متكاملة تدفع الأعمال نحو مستقبل أكثر تطورًا. من تطوير المواقع والتطبيقات إلى الاستشارات التقنية والحلول السحابية، نعمل بشغف لنمنحك الأدوات التي تحتاجها للنجاح في العالم الرقمي. 🚀",
    "portfolio.title": "أعمالنا",
    "portfolio.subtitle": "اكتشف مجموعة من مشاريعنا المتميزة",
    "contact.title": "تواصل معنا",
    "contact.subtitle": "نحن هنا للإجابة على استفساراتك",
    "contact.name": "الاسم",
    "contact.email": "البريد الإلكتروني",
    "contact.message": "الرسالة",
    "contact.submit": "إرسال",
    "contact.getInTouch": "تواصل معنا",
    "contact.phone": "الهاتف",
    "contact.address": "العنوان",
    "contact.addressValue": "الرياض، المملكة العربية السعودية",
    "contact.socialMedia": "وسائل التواصل",
    "contact.whatsapp": "تواصل عبر واتساب",
    "contact.aiAssistant": "المساعد الذكي",
    "contact.aiPlaceholder": "اسأل عن خدماتنا...",
    "contact.aiAsk": "اسأل المساعد",
    "contact.aiProcessing": "جاري المعالجة...",
    "contact.successTitle": "تم الإرسال بنجاح",
    "contact.successMessage": "شكراً لتواصلك معنا، سنرد عليك في أقرب وقت.",
    "contact.aiError": "حدث خطأ",
    "contact.aiErrorMessage": "لم نتمكن من الاتصال بالمساعد الذكي، الرجاء المحاولة مرة أخرى.",
    "contact.aiEmptyQuery": "الرسالة فارغة",
    "contact.aiEmptyQueryMessage": "الرجاء كتابة سؤالك قبل الإرسال.",
    "partners.title": "شركائنا",
    "faq.title": "الأسئلة الشائعة",
    "faq.description": "ندرك أن لديك العديد من الأسئلة حول خدماتنا وكيف يمكننا مساعدتك في تحقيق أهدافك الرقمية. لذلك، قمنا بجمع أكثر الاستفسارات شيوعًا وأجبنا عليها لمساعدتك في فهم خدماتنا بشكل أفضل. إذا لم تجد إجابتك هنا، لا تتردد في التواصل معنا، وسنكون سعداء بالإجابة على جميع استفساراتك.",
    "faq.askButton": "اطرح سؤلك",
    "faq.q1": "ما هي الخدمات التي تقدمونها؟",
    "faq.a1": "نقدم مجموعة متكاملة من الخدمات تشمل تصميم وتطوير المواقع الإلكترونية، تطوير تطبيقات الجوال، التسويق الرقمي، حلول الأمان السيبراني، الاستشارات التقنية، والحلول السحابية، مما يضمن لك حلولًا رقمية متكاملة تلبي احتياجاتك.",
    "faq.q2": "هل تصممون مواقع متوافقة مع محركات البحث (SEO)؟",
    "faq.a2": "نعم، جميع مواقعنا مُحسّنة لمحركات البحث باستخدام أحدث تقنيات الـ SEO، مما يساعد على تحسين ظهور موقعك في نتائج البحث وزيادة عدد الزوار بشكل فعال.",
    "faq.q3": "ما هي المدة الزمنية لتنفيذ المشروع؟",
    "faq.a3": "تختلف المدة الزمنية حسب حجم وتعقيد المشروع. نحن نحرص على تحديد جدول زمني واضح ودقيق لكل مشروع ونلتزم بالمواعيد المتفق عليها مع العميل لضمان تسليم المشروع في الوقت المحدد.",
    "faq.q4": "هل تقدمون دعمًا فنيًا بعد تسليم المشروع؟",
    "faq.a4": "نعم، نقدم خدمات الدعم الفني المستمر بعد تسليم المشروع، ونوفر خطط دعم مختلفة تتناسب مع احتياجاتك لضمان استمرارية عمل موقعك أو تطبيقك بكفاءة عالية."
  },
  en: {
    "home": "Home",
    "services": "Services",
    "about": "About",
    "portfolio": "Portfolio",
    "contact": "Contact",
    "hero.title": "Driving Digital Transformation Through Innovation",
    "hero.subtitle": "We deliver integrated technological solutions that combine creativity and excellence to help companies grow in the digital era",
    "cta.button": "Contact Us",
    "services.title": "Our Distinguished Services",
    "service1.title": "Web Development",
    "service1.desc": "Design and develop exceptional responsive websites using the latest technologies",
    "service2.title": "App Development",
    "service2.desc": "Develop high-performance mobile and desktop applications for iOS and Android",
    "service3.title": "AI Services",
    "service3.desc": "Advanced artificial intelligence solutions to improve business operations and enhance productivity",
    "service4.title": "Technical Consulting",
    "service4.desc": "We provide technical consultations to help companies make the right technical decisions",
    "footer.copyright": "All rights reserved",
    "about.title": "About Us",
    "about.subtitle": "We lead digital transformation for companies through innovation and excellence",
    "about.description": "At Olu, we strive to provide innovative technical solutions that meet the diverse needs of our clients. We believe in the power of technology to enhance business performance and achieve sustainable growth.",
    "portfolio.title": "Our Portfolio",
    "portfolio.subtitle": "Discover a collection of our outstanding projects",
    "contact.title": "Contact Us",
    "contact.subtitle": "We're here to answer your inquiries",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.submit": "Submit",
    "contact.getInTouch": "Get in Touch",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.addressValue": "Riyadh, Saudi Arabia",
    "contact.socialMedia": "Social Media",
    "contact.whatsapp": "Contact via WhatsApp",
    "contact.aiAssistant": "AI Assistant",
    "contact.aiPlaceholder": "Ask about our services...",
    "contact.aiAsk": "Ask Assistant",
    "contact.aiProcessing": "Processing...",
    "contact.successTitle": "Message Sent",
    "contact.successMessage": "Thank you for contacting us. We'll respond as soon as possible.",
    "contact.aiError": "Error Occurred",
    "contact.aiErrorMessage": "We couldn't connect to the AI assistant. Please try again.",
    "contact.aiEmptyQuery": "Empty Message",
    "contact.aiEmptyQueryMessage": "Please write your question before sending.",
    "partners.title": "Our Partners",
    "faq.title": "Frequently Asked Questions",
    "faq.description": "We understand that you have many questions about our services and how we can help you achieve your digital goals. We've collected the most common inquiries to help you understand our services better. If you don't find your answer here, feel free to contact us.",
    "faq.askButton": "Ask a Question",
    "faq.q1": "What services do you provide?",
    "faq.a1": "We offer a comprehensive range of services including website design and development, mobile app development, digital marketing, cybersecurity solutions, technical consultations, and cloud solutions, ensuring integrated digital solutions that meet your needs.",
    "faq.q2": "Do you design websites compatible with search engines (SEO)?",
    "faq.a2": "Yes, all our websites are optimized for search engines using the latest SEO techniques, which helps improve your website's visibility in search results and effectively increase the number of visitors.",
    "faq.q3": "What is the timeframe for project implementation?",
    "faq.a3": "The timeframe varies depending on the size and complexity of the project. We are keen to set a clear and precise timeline for each project and adhere to the dates agreed upon with the client to ensure that the project is delivered on time.",
    "faq.q4": "Do you provide technical support after project delivery?",
    "faq.a4": "Yes, we provide ongoing technical support services after project delivery, and we offer different support plans that suit your needs to ensure the continuity of your website or application's efficient operation."
  },
  fr: {
    "home": "Accueil",
    "services": "Services",
    "about": "À propos",
    "portfolio": "Portfolio",
    "contact": "Contact",
    "hero.title": "Conduire la transformation numérique par l'innovation",
    "hero.subtitle": "Nous proposons des solutions technologiques intégrées qui combinent créativité et excellence pour aider les entreprises à se développer à l'ère numérique",
    "cta.button": "Contactez-nous",
    "services.title": "Nos services distingués",
    "services.description": "Nous fournissons des solutions numériques innovantes comprenant le développement de sites web et d'applications, des conseils techniques, des solutions cloud et la sécurité de l'information. Notre objectif est d'améliorer votre performance numérique grâce à des stratégies avancées garantissant efficacité, sécurité et expansion durable. 🚀",
    "services.viewAll": "Voir tous les services",
    "service1.title": "Développement Web",
    "service1.desc": "Conception et développement de sites web exceptionnels et réactifs utilisant les dernières technologies",
    "service2.title": "Développement d'Applications",
    "service2.desc": "Développement d'applications mobiles et de bureau à haute performance pour iOS et Android",
    "service3.title": "Services IA",
    "service3.desc": "Solutions d'intelligence artificielle avancées pour améliorer les opérations commerciales et augmenter la productivité",
    "service4.title": "Conseil Technique",
    "service4.desc": "Nous fournissons des consultations techniques pour aider les entreprises à prendre les bonnes décisions techniques",
    "footer.copyright": "Tous droits réservés",
    "about.title": "À propos de nous",
    "about.subtitle": "Nous dirigeons la transformation numérique des entreprises grâce à l'innovation et l'excellence",
    "about.description": "Chez Olu, nous nous efforçons de fournir des solutions techniques innovantes qui répondent aux divers besoins de nos clients. Nous croyons au pouvoir de la technologie pour améliorer la performance des entreprises et réaliser une croissance durable.",
    "portfolio.title": "Notre Portfolio",
    "portfolio.subtitle": "Découvrez une collection de nos projets exceptionnels",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Nous sommes là pour répondre à vos questions",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.submit": "Soumettre",
    "contact.getInTouch": "Entrer en contact",
    "contact.phone": "Téléphone",
    "contact.address": "Adresse",
    "contact.addressValue": "Riyad, Arabie Saoudite",
    "contact.socialMedia": "Réseaux Sociaux",
    "contact.whatsapp": "Contact via WhatsApp",
    "contact.aiAssistant": "Assistant IA",
    "contact.aiPlaceholder": "Demandez à propos de nos services...",
    "contact.aiAsk": "Demander à l'assistant",
    "contact.aiProcessing": "Traitement en cours...",
    "contact.successTitle": "Message Envoyé",
    "contact.successMessage": "Merci de nous avoir contactés. Nous vous répondrons dès que possible.",
    "contact.aiError": "Erreur survenue",
    "contact.aiErrorMessage": "Nous n'avons pas pu nous connecter à l'assistant IA. Veuillez réessayer.",
    "contact.aiEmptyQuery": "Message vide",
    "contact.aiEmptyQueryMessage": "Veuillez écrire votre question avant d'envoyer.",
    "partners.title": "Nos Partenaires",
    "faq.title": "Questions Fréquemment Posées",
    "faq.description": "Nous comprenons que vous avez de nombreuses questions sur nos services et comment nous pouvons vous aider à atteindre vos objectifs numériques. Nous avons rassemblé les demandes les plus courantes pour vous aider à mieux comprendre nos services. Si vous ne trouvez pas votre réponse ici, n'hésitez pas à nous contacter.",
    "faq.askButton": "Poser une question",
    "faq.q1": "Quels services proposez-vous?",
    "faq.a1": "Nous offrons une gamme complète de services comprenant la conception et le développement de sites web, le développement d'applications mobiles, le marketing numérique, des solutions de cybersécurité, des consultations techniques et des solutions cloud, assurant des solutions numériques intégrées qui répondent à vos besoins.",
    "faq.q2": "Concevez-vous des sites web compatibles avec les moteurs de recherche (SEO)?",
    "faq.a2": "Oui, tous nos sites web sont optimisés pour les moteurs de recherche en utilisant les dernières techniques SEO, ce qui aide à améliorer la visibilité de votre site web dans les résultats de recherche et à augmenter efficacement le nombre de visiteurs.",
    "faq.q3": "Quel est le délai de mise en œuvre du projet?",
    "faq.a3": "Le délai varie en fonction de la taille et de la complexité du projet. Nous tenons à établir un calendrier clair et précis pour chaque projet et à respecter les dates convenues avec le client pour garantir que le projet soit livré dans les délais.",
    "faq.q4": "Fournissez-vous un support technique après la livraison du projet?",
    "faq.a4": "Oui, nous fournissons des services de support technique continus après la livraison du projet, et nous proposons différents plans de support qui conviennent à vos besoins pour assurer la continuité du fonctionnement efficace de votre site web ou application."
  },
  tr: {
    "home": "Ana Sayfa",
    "services": "Hizmetler",
    "about": "Hakkımızda",
    "portfolio": "Portföy",
    "contact": "İletişim",
    "hero.title": "İnovasyon Yoluyla Dijital Dönüşümü Yönetmek",
    "hero.subtitle": "Şirketlerin dijital çağda büyümesine yardımcı olmak için yaratıcılık ve mükemmelliği birleştiren entegre teknolojik çözümler sunuyoruz",
    "cta.button": "Bize Ulaşın",
    "services.title": "Seçkin Hizmetlerimiz",
    "services.description": "Web ve uygulama geliştirme, teknik danışmanlık, bulut çözümleri ve bilgi güvenliği içeren yenilikçi dijital çözümler sunuyoruz. Amacımız, verimlilik, güvenlik ve sürdürülebilir genişleme sağlayan gelişmiş stratejilerle dijital performansınızı iyileştirmektir. 🚀",
    "services.viewAll": "Tüm Hizmetleri Görüntüle",
    "service1.title": "Web Geliştirme",
    "service1.desc": "En son teknolojileri kullanarak olağanüstü duyarlı web siteleri tasarlayın ve geliştirin",
    "service2.title": "Uygulama Geliştirme",
    "service2.desc": "iOS ve Android için yüksek performanslı mobil ve masaüstü uygulamaları geliştirin",
    "service3.title": "Yapay Zeka Hizmetleri",
    "service3.desc": "İş operasyonlarını iyileştirmek ve üretkenliği artırmak için gelişmiş yapay zeka çözümleri",
    "service4.title": "Teknik Danışmanlık",
    "service4.desc": "Şirketlerin doğru teknik kararları vermelerine yardımcı olmak için teknik danışmanlık hizmetleri sunuyoruz",
    "footer.copyright": "Tüm hakları saklıdır",
    "about.title": "Hakkımızda",
    "about.subtitle": "İnovasyon ve mükemmellik yoluyla şirketler için dijital dönüşüme öncülük ediyoruz",
    "about.description": "Olu'da, müşterilerimizin çeşitli ihtiyaçlarını karşılayan yenilikçi teknik çözümler sunmak için çalışıyoruz. İş performansını artırmak ve sürdürülebilir büyüme sağlamak için teknolojinin gücüne inanıyoruz.",
    "portfolio.title": "Portföyümüz",
    "portfolio.subtitle": "Olağanüstü projelerimizin bir koleksiyonunu keşfedin",
    "contact.title": "Bize Ulaşın",
    "contact.subtitle": "Sorularınızı yanıtlamak için buradayız",
    "contact.name": "İsim",
    "contact.email": "E-posta",
    "contact.message": "Mesaj",
    "contact.submit": "Gönder",
    "contact.getInTouch": "İletişime Geçin",
    "contact.phone": "Telefon",
    "contact.address": "Adres",
    "contact.addressValue": "Riyad, Suudi Arabistan",
    "contact.socialMedia": "Sosyal Medya",
    "contact.whatsapp": "WhatsApp ile iletişim",
    "contact.aiAssistant": "Yapay Zeka Asistanı",
    "contact.aiPlaceholder": "Hizmetlerimiz hakkında sorun...",
    "contact.aiAsk": "Asistana Sor",
    "contact.aiProcessing": "İşleniyor...",
    "contact.successTitle": "Mesaj Gönderildi",
    "contact.successMessage": "Bizimle iletişime geçtiğiniz için teşekkür ederiz. En kısa sürede yanıt vereceğiz.",
    "contact.aiError": "Hata Oluştu",
    "contact.aiErrorMessage": "Yapay zeka asistanına bağlanamadık. Lütfen tekrar deneyin.",
    "contact.aiEmptyQuery": "Boş Mesaj",
    "contact.aiEmptyQueryMessage": "Göndermeden önce lütfen sorunuzu yazın.",
    "partners.title": "Ortaklarımız",
    "faq.title": "Sık Sorulan Sorular",
    "faq.description": "Hizmetlerimiz ve dijital hedeflerinize ulaşmanıza nasıl yardımcı olabileceğimiz konusunda birçok sorunuz olduğunu anlıyoruz. Hizmetlerimizi daha iyi anlamanıza yardımcı olmak için en yaygın soruları topladık. Cevabınızı burada bulamazsanız, bizimle iletişime geçmekten çekinmeyin.",
    "faq.askButton": "Soru Sor",
    "faq.q1": "Hangi hizmetleri sunuyorsunuz?",
    "faq.a1": "Web sitesi tasarımı ve geliştirme, mobil uygulama geliştirme, dijital pazarlama, siber güvenlik çözümleri, teknik danışmanlık ve bulut çözümleri dahil olmak üzere kapsamlı bir hizmet yelpazesi sunuyoruz ve ihtiyaçlarınızı karşılayan entegre dijital çözümler sağlıyoruz.",
    "faq.q2": "Arama motorlarıyla uyumlu (SEO) web siteleri tasarlıyor musunuz?",
    "faq.a2": "Evet, tüm web sitelerimiz en son SEO teknikleri kullanılarak arama motorları için optimize edilmiştir, bu da web sitenizin arama sonuçlarındaki görünürlüğünü artırmaya ve ziyaretçi sayısını etkili bir şekilde artırmaya yardımcı olur.",
    "faq.q3": "Proje uygulama süresi nedir?",
    "faq.a3": "Süre, projenin büyüklüğüne ve karmaşıklığına bağlı olarak değişir. Her proje için net ve kesin bir zaman çizelgesi belirlemek ve projenin zamanında teslim edilmesini sağlamak için müşteriyle kararlaştırılan tarihlere bağlı kalmaya özen gösteriyoruz.",
    "faq.q4": "Proje tesliminden sonra teknik destek sağlıyor musunuz?",
    "faq.a4": "Evet, proje tesliminden sonra sürekli teknik destek hizmetleri sunuyoruz ve web sitenizin veya uygulamanızın verimli çalışmasının sürekliliğini sağlamak için ihtiyaçlarınıza uygun farklı destek planları sunuyoruz."
  },
  zh: {
    "home": "首页",
    "services": "服务",
    "about": "关于我们",
    "portfolio": "作品集",
    "contact": "联系我们",
    "hero.title": "通过创新推动数字化转型",
    "hero.subtitle": "我们提供结合创造力和卓越性的综合技术解决方案，帮助企业在数字时代成长",
    "cta.button": "联系我们",
    "services.title": "我们的特色服务",
    "services.description": "我们提供创新的数字解决方案，包括网站和应用程序开发、技术咨询、云解决方案和信息安全。我们的目标是通过确保效率、安全性和可持续扩展的先进策略提高您的数字性能。🚀",
    "services.viewAll": "查看所有服务",
    "service1.title": "网站开发",
    "service1.desc": "使用最新技术设计和开发出色的响应式网站",
    "service2.title": "应用程序开发",
    "service2.desc": "为iOS和Android开发高性能的移动和桌面应用程序",
    "service3.title": "人工智能服务",
    "service3.desc": "先进的人工智能解决方案，改善业务运营并提高生产力",
    "service4.title": "技术咨询",
    "service4.desc": "我们提供技术咨询，帮助公司做出正确的技术决策",
    "footer.copyright": "保留所有权利",
    "about.title": "关于我们",
    "about.subtitle": "我们通过创新和卓越引领公司的数字化转型",
    "about.description": "在Olu，我们致力于提供创新的技术解决方案，满足客户的多样化需求。我们相信技术的力量可以提高业务绩效并实现可持续增长。",
    "portfolio.title": "我们的作品集",
    "portfolio.subtitle": "探索我们出色项目的集合",
    "contact.title": "联系我们",
    "contact.subtitle": "我们在这里回答您的询问",
    "contact.name": "姓名",
    "contact.email": "电子邮件",
    "contact.message": "留言",
    "contact.submit": "提交",
    "contact.getInTouch": "联系我们",
    "contact.phone": "电话",
    "contact.address": "地址",
    "contact.addressValue": "利雅得，沙特阿拉伯",
    "contact.socialMedia": "社交媒体",
    "contact.whatsapp": "通过WhatsApp联系",
    "contact.aiAssistant": "人工智能助手",
    "contact.aiPlaceholder": "询问我们的服务...",
    "contact.aiAsk": "询问助手",
    "contact.aiProcessing": "处理中...",
    "contact.successTitle": "消息已发送",
    "contact.successMessage": "感谢您联系我们。我们将尽快回复。",
    "contact.aiError": "发生错误",
    "contact.aiErrorMessage": "我们无法连接到人工智能助手。请重试。",
    "contact.aiEmptyQuery": "空消息",
    "contact.aiEmptyQueryMessage": "请在发送前写下您的问题。",
    "partners.title": "我们的合作伙伴",
    "faq.title": "常见问题",
    "faq.description": "我们理解您对我们的服务以及我们如何帮助您实现数字目标有许多问题。我们收集了最常见的问题，以帮助您更好地了解我们的服务。如果您在这里找不到您的答案，请随时联系我们。",
    "faq.askButton": "提问",
    "faq.q1": "您提供哪些服务？",
    "faq.a1": "我们提供全面的服务，包括网站设计和开发、移动应用程序开发、数字营销、网络安全解决方案、技术咨询和云解决方案，确保满足您需求的综合数字解决方案。",
    "faq.q2": "您是否设计与搜索引擎兼容的网站（SEO）？",
    "faq.a2": "是的，我们所有的网站都使用最新的SEO技术进行了优化，这有助于提高您网站在搜索结果中的可见性，并有效增加访问者数量。",
    "faq.q3": "项目实施的时间框架是什么？",
    "faq.a3": "时间范围取决于项目的规模和复杂性。我们致力于为每个项目设定明确和精确的时间表，并坚持与客户约定的日期，以确保项目按时交付。",
    "faq.q4": "您是否在项目交付后提供技术支持？",
    "faq.a4": "是的，我们在项目交付后提供持续的技术支持服务，并提供适合您需求的不同支持计划，以确保您的网站或应用程序持续高效运行。"
  },
  es: {
    "home": "Inicio",
    "services": "Servicios",
    "about": "Acerca de",
    "portfolio": "Portafolio",
    "contact": "Contacto",
    "hero.title": "Impulsando la Transformación Digital a través de la Innovación",
    "hero.subtitle": "Ofrecemos soluciones tecnológicas integradas que combinan creatividad y excelencia para ayudar a las empresas a crecer en la era digital",
    "cta.button": "Contáctenos",
    "services.title": "Nuestros Servicios Distinguidos",
    "services.description": "Proporcionamos soluciones digitales innovadoras que incluyen desarrollo de sitios web y aplicaciones, consultoría técnica, soluciones en la nube y seguridad de la información. Nuestro objetivo es mejorar su rendimiento digital a través de estrategias avanzadas que garantizan eficiencia, seguridad y expansión sostenible. 🚀",
    "services.viewAll": "Ver Todos los Servicios",
    "service1.title": "Desarrollo Web",
    "service1.desc": "Diseño y desarrollo de sitios web excepcionales y receptivos utilizando las últimas tecnologías",
    "service2.title": "Desarrollo de Aplicaciones",
    "service2.desc": "Desarrollo de aplicaciones móviles y de escritorio de alto rendimiento para iOS y Android",
    "service3.title": "Servicios de IA",
    "service3.desc": "Soluciones avanzadas de inteligencia artificial para mejorar las operaciones comerciales y aumentar la productividad",
    "service4.title": "Consultoría Técnica",
    "service4.desc": "Proporcionamos consultas técnicas para ayudar a las empresas a tomar las decisiones técnicas correctas",
    "footer.copyright": "Todos los derechos reservados",
    "about.title": "Acerca de Nosotros",
    "about.subtitle": "Lideramos la transformación digital para empresas a través de la innovación y la excelencia",
    "about.description": "En Olu, nos esforzamos por proporcionar soluciones técnicas innovadoras que satisfagan las diversas necesidades de nuestros clientes. Creemos en el poder de la tecnología para mejorar el rendimiento empresarial y lograr un crecimiento sostenible.",
    "portfolio.title": "Nuestro Portafolio",
    "portfolio.subtitle": "Descubra una colección de nuestros proyectos destacados",
    "contact.title": "Contáctenos",
    "contact.subtitle": "Estamos aquí para responder a sus consultas",
    "contact.name": "Nombre",
    "contact.email": "Correo electrónico",
    "contact.message": "Mensaje",
    "contact.submit": "Enviar",
    "contact.getInTouch": "Póngase en Contacto",
    "contact.phone": "Teléfono",
    "contact.address": "Dirección",
    "contact.addressValue": "Riad, Arabia Saudita",
    "contact.socialMedia": "Redes Sociales",
    "contact.whatsapp": "Contactar vía WhatsApp",
    "contact.aiAssistant": "Asistente de IA",
    "contact.aiPlaceholder": "Pregunte sobre nuestros servicios...",
    "contact.aiAsk": "Preguntar al Asistente",
    "contact.aiProcessing": "Procesando...",
    "contact.successTitle": "Mensaje Enviado",
    "contact.successMessage": "Gracias por contactarnos. Responderemos lo antes posible.",
    "contact.aiError": "Ocurrió un Error",
    "contact.aiErrorMessage": "No pudimos conectar con el asistente de IA. Por favor, inténtelo de nuevo.",
    "contact.aiEmptyQuery": "Mensaje Vacío",
    "contact.aiEmptyQueryMessage": "Por favor, escriba su pregunta antes de enviar.",
    "partners.title": "Nuestros Socios",
    "faq.title": "Preguntas Frecuentes",
    "faq.description": "Entendemos que tiene muchas preguntas sobre nuestros servicios y cómo podemos ayudarlo a alcanzar sus objetivos digitales. Hemos recopilado las consultas más comunes para ayudarlo a comprender mejor nuestros servicios. Si no encuentra su respuesta aquí, no dude en contactarnos.",
    "faq.askButton": "Hacer una Pregunta",
    "faq.q1": "¿Qué servicios proporcionan?",
    "faq.a1": "Ofrecemos una gama completa de servicios que incluyen diseño y desarrollo de sitios web, desarrollo de aplicaciones móviles, marketing digital, soluciones de ciberseguridad, consultas técnicas y soluciones en la nube, asegurando soluciones digitales integradas que satisfacen sus necesidades.",
    "faq.q2": "¿Diseñan sitios web compatibles con motores de búsqueda (SEO)?",
    "faq.a2": "Sí, todos nuestros sitios web están optimizados para motores de búsqueda utilizando las últimas técnicas de SEO, lo que ayuda a mejorar la visibilidad de su sitio web en los resultados de búsqueda y aumentar eficazmente el número de visitantes.",
    "faq.q3": "¿Cuál es el plazo para la implementación del proyecto?",
    "faq.a3": "El plazo varía según el tamaño y la complejidad del proyecto. Nos preocupamos por establecer un cronograma claro y preciso para cada proyecto y cumplir con las fechas acordadas con el cliente para garantizar que el proyecto se entregue a tiempo.",
    "faq.q4": "¿Proporcionan soporte técnico después de la entrega del proyecto?",
    "faq.a4": "Sí, proporcionamos servicios de soporte técnico continuo después de la entrega del proyecto, y ofrecemos diferentes planes de soporte que se adaptan a sus necesidades para garantizar la continuidad del funcionamiento eficiente de su sitio web o aplicación."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>("en");
  const [dir, setDir] = useState<DirectionType>("ltr");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as LanguageCode | null;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage);
    } else {
      // Detect browser language
      const browserLang = navigator.language.split("-")[0];
      if (browserLang === "ar") {
        setLanguage("ar");
      }
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    const htmlDir = language === "ar" ? "rtl" : "ltr";
    setDir(htmlDir);
    document.documentElement.setAttribute("dir", htmlDir);
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    if (translations["en"] && translations["en"][key]) {
      return translations["en"][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
