// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyyrqdnfirapivtlnuqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5eXJxZG5maXJhcGl2dGxudXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjMyMDYsImV4cCI6MjA1OTA5OTIwNn0.zvAlTs57ORdbBTukbCB09wWexlZ-PE-1Miftfw3uLzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);